"""
v2 hex-first change system (`s19app-changeset`) — re-export facade.

Public surface of the ``changes`` package (batch-07, HLR-001/HLR-002): the
object model and change summary (``model.py``), the JSON reader/writer,
rule-code constants, and S19 emitter (``io.py``), the intra-document
collision rule (``validate.py``), and the apply engine (``apply.py``).
Import from here; the modules stay the implementation detail.
"""

from .model import (
    CHANGES_ARTIFACT,
    DISPOSITION_APPLIED,
    DISPOSITION_BLOCKED,
    DISPOSITION_DOMAIN,
    DISPOSITION_SKIPPED_NO_IMAGE,
    DISPOSITION_SKIPPED_OUTSIDE,
    DISPOSITION_SKIPPED_PARTIAL,
    LINKAGE_A2L,
    LINKAGE_BOTH,
    LINKAGE_MAC,
    LINKAGE_STANDALONE,
    ChangeDocument,
    ChangeEntry,
    ChangeSummary,
    ChangeSummaryEntry,
    MemoryStatus,
)
from .validate import CHG_COLLISION, collision_issues
from .display import (
    ASCII_PLACEHOLDER,
    PRINTABLE_ASCII_MAX,
    PRINTABLE_ASCII_MIN,
    MemoryValueRendering,
    format_memory_value,
)
from .apply import (
    CHG_HEX_SAVE_UNSUPPORTED,
    apply_change_document,
    classify_containment,
    save_patched_image,
)
from .io import (
    emit_s19_from_mem_map,
    CHG_ADDRESS_SYNTAX,
    CHG_BYTES_SYNTAX,
    CHG_ENCODE_FAIL,
    CHG_ENCODING_UNKNOWN,
    CHG_FORMAT,
    CHG_KIND_UNKNOWN,
    CHG_V1_FORMAT,
    CHG_VALUE_EMPTY,
    CHG_VALUE_MODE_UNKNOWN,
    DEFAULT_CHANGE_FILE_NAME,
    DOCUMENT_KINDS,
    FORMAT_ID,
    FORMAT_VERSION,
    MF_BAD_STRUCTURE,
    MF_ENTRY_COUNT_CEILING,
    MF_ENTRY_LIMIT,
    MF_JSON_PARSE,
    MF_PATH_UNRESOLVED,
    MF_RUN_LENGTH_CEILING,
    MF_SIZE_CAP,
    MF_WRITE_CONTAINMENT,
    READ_SIZE_CAP_BYTES,
    V1_FORMAT_ID,
    VALUE_MODES,
    read_change_document,
    serialize_change_document,
    write_change_document,
)

__all__ = [
    "CHANGES_ARTIFACT",
    "ChangeDocument",
    "ChangeEntry",
    "ChangeSummary",
    "ChangeSummaryEntry",
    "MemoryStatus",
    "DISPOSITION_APPLIED",
    "DISPOSITION_BLOCKED",
    "DISPOSITION_DOMAIN",
    "DISPOSITION_SKIPPED_NO_IMAGE",
    "DISPOSITION_SKIPPED_OUTSIDE",
    "DISPOSITION_SKIPPED_PARTIAL",
    "LINKAGE_A2L",
    "LINKAGE_BOTH",
    "LINKAGE_MAC",
    "LINKAGE_STANDALONE",
    "CHG_COLLISION",
    "collision_issues",
    "ASCII_PLACEHOLDER",
    "PRINTABLE_ASCII_MAX",
    "PRINTABLE_ASCII_MIN",
    "MemoryValueRendering",
    "format_memory_value",
    "CHG_HEX_SAVE_UNSUPPORTED",
    "apply_change_document",
    "classify_containment",
    "save_patched_image",
    "emit_s19_from_mem_map",
    "CHG_ADDRESS_SYNTAX",
    "CHG_BYTES_SYNTAX",
    "CHG_ENCODE_FAIL",
    "CHG_ENCODING_UNKNOWN",
    "CHG_FORMAT",
    "CHG_KIND_UNKNOWN",
    "CHG_V1_FORMAT",
    "CHG_VALUE_EMPTY",
    "CHG_VALUE_MODE_UNKNOWN",
    "DEFAULT_CHANGE_FILE_NAME",
    "DOCUMENT_KINDS",
    "FORMAT_ID",
    "FORMAT_VERSION",
    "MF_BAD_STRUCTURE",
    "MF_ENTRY_COUNT_CEILING",
    "MF_ENTRY_LIMIT",
    "MF_JSON_PARSE",
    "MF_PATH_UNRESOLVED",
    "MF_RUN_LENGTH_CEILING",
    "MF_SIZE_CAP",
    "MF_WRITE_CONTAINMENT",
    "READ_SIZE_CAP_BYTES",
    "V1_FORMAT_ID",
    "VALUE_MODES",
    "read_change_document",
    "serialize_change_document",
    "write_change_document",
]
