"""
Computed-address census — how s19_app addresses its widgets, measured by AST.

This module answers one question and refuses to let its answer be copied: **which
call sites address a widget by a selector the reader cannot resolve by grep?**
That is the sizing input for the `C-54` Information Flow Contract, whose `address`
and `consumers` fields only mean something if the set of address forms is known.

Why it is a command and not a table in a document: three separate censuses of this
same surface have now disagreed, and every one of them was accurate the day it was
written. A grep census (2026-08-13) reported 1586 sites with 53 computed ones "all
of one shape"; an AST pass refuted all three figures; and a third pass refuted the
second's totals in turn. The pattern is the one `tools/id_registry.py` states for
its own domain — *"an unstated grep pattern is an unstated definition"* — so this
module states its definitions as code and prints the numbers on demand.

The three definitions that decide every figure below, and each is a correction of a
measurement that went wrong before it:

1. :data:`SELECTOR_RE` — a ``#`` or ``.`` must be followed **immediately** by an
   identifier character or an interpolation. A criterion of merely *"starts with #
   or ."* sweeps in markdown headings (``f"## Variant: {n}"``), prose ellipsis
   (``f"... {n} more ranges"``) and hex colours, and inflates the count by 2.5x.

2. **Format specs are not strings.** ``f"{value:#x}"`` holds a nested ``JoinedStr``
   in the AST — the ``:#x`` spec itself — which reads as an f-string of shape
   ``#x``. Twelve of these exist in the tree and not one is a selector.
   :func:`format_spec_nodes` marks them for exclusion.

3. :data:`ADDRESS_PARAMS` is **derived from Textual, never written**. Textual resolves
   a selector through many doors, and ``pilot.click(f"#{widget_id}")`` is as much a
   computed address as ``query_one``. Written by hand, this set held a name that is not
   a Textual API and missed 16 that are — **and the census printed the same numbers
   either way**, which is why no reading could have caught it.
   :func:`derive_address_params` asks Textual itself, in two composing passes:
   annotation shape finds the query family, then taint seeded from those reaches the
   plain-``str`` methods no annotation reveals. Measured: seeding taint from the raw
   sinks alone reaches 1 of 6; seeding from the annotation pass reaches 6 of 6, plus
   23 per-id APIs on ``Tabs``/``TabbedContent``/``ContentSwitcher`` that nobody watched.

4. **Parameters, not arguments.** Not every argument of an address call is an address:
   ``mount(*widgets, before="#foo")`` takes widgets positionally and the selector by
   keyword only. Counting all arguments reported ``*widgets`` as an unresolvable
   address. :data:`ADDRESS_PARAMS` and :data:`FIRST_POSITIONAL_SELECTOR` narrow it
   to the parameter that actually carries a selector — both derived, not listed. This defect was found by the
   `AT-B83-08` invariant the moment ``mount`` entered the set — not by review.

Example::

    python tools/address_census.py            # census of the repo it lives in
    python tools/address_census.py --json     # machine-readable, for a guard
"""

from __future__ import annotations

import argparse
import ast
import functools
import inspect
import json
import re
import sys
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterator

#: The query family — used only to split the report between "the door everyone watches"
#: and the others. Not the address set; see :data:`ADDRESS_APIS`.
QUERY_APIS: frozenset[str] = frozenset({
    "query", "query_one", "query_exactly_one", "query_ancestor",
    "query_children", "query_one_optional",
})

#: Every address API, and WHICH PARAMETER carries the selector — a snapshot of what
#: :func:`derive_address_params` returns, pinned at ``textual 8.2.8``.
#:
#: **Nothing here is hand-written.** It is generated by two derivations that compose:
#: annotation shape finds the query family, and taint propagates from those to the
#: methods whose parameter is a plain ``str``. ``tests/test_address_census.py`` compares
#: this snapshot against the live derivation in both directions, so it cannot drift.
#:
#: It is a constant rather than a live call because the derivation costs ~18s and
#: importing this module must not pay that. The guard pays it once per suite run.
#:
#: **Three rules narrow it, and each is a rule rather than a list of names** — the
#: distinction that keeps the derivation honest (see :func:`is_candidate_method` and R1
#: in :func:`_textual_methods`):
#:
#: * a selector parameter must be **annotated** as accepting ``str``
#: * **private** methods are excluded — a consumer does not call Textual's internals
#: * **reactive hooks** (``watch_*``/``validate_*``/``compute_*``) are excluded: the
#:   framework calls them, a consumer never does
#:
#: Measured: 48 -> 40 entries, and **not one of the 8 removed is called anywhere in
#: s19_app** (`git grep`). The six that were a hand-maintained list until Inc-2 all
#: survive all three rules.
ADDRESS_PARAMS: dict[str, frozenset[str]] = {
    'action_add_class':      frozenset({'selector'}),
    'action_focus':          frozenset({'widget_id'}),
    'action_remove_class':   frozenset({'selector'}),
    'action_toggle_class':   frozenset({'selector'}),
    'add_pane':              frozenset({'after', 'before'}),
    'add_tab':               frozenset({'after', 'before'}),
    'click':                 frozenset({'widget'}),
    'disable':               frozenset({'tab_id'}),
    'disable_tab':           frozenset({'tab_id'}),
    'double_click':          frozenset({'widget'}),
    'enable':                frozenset({'tab_id'}),
    'enable_tab':            frozenset({'tab_id'}),
    'exclude':               frozenset({'selector'}),
    'filter':                frozenset({'selector'}),
    'focus_next':            frozenset({'selector'}),
    'focus_previous':        frozenset({'selector'}),
    'get_child_by_id':       frozenset({'id'}),
    'get_content_tab':       frozenset({'tab_id'}),
    'get_tab':               frozenset({'tab_id'}),
    'get_widget_by_id':      frozenset({'id'}),
    'hide':                  frozenset({'tab_id'}),
    'hide_tab':              frozenset({'tab_id'}),
    'hover':                 frozenset({'widget'}),
    'mount':                 frozenset({'after', 'before'}),
    'mount_all':             frozenset({'after', 'before'}),
    'mount_compose':         frozenset({'after', 'before'}),
    'mouse_down':            frozenset({'widget'}),
    'mouse_up':              frozenset({'widget'}),
    'query':                 frozenset({'selector'}),
    'query_ancestor':        frozenset({'selector'}),
    'query_children':        frozenset({'selector'}),
    'query_exactly_one':     frozenset({'selector'}),
    'query_one':             frozenset({'selector'}),
    'query_one_optional':    frozenset({'selector'}),
    'remove_children':       frozenset({'selector'}),
    'remove_pane':           frozenset({'pane_id'}),
    'remove_tab':            frozenset({'tab_or_id'}),
    'show':                  frozenset({'tab_id'}),
    'show_tab':              frozenset({'tab_id'}),
    'triple_click':          frozenset({'widget'}),
}

#: APIs whose FIRST parameter is the selector — also derived, never listed.
#:
#: Not every argument of an address call is an address. ``mount(*widgets, before="#foo")``
#: takes widgets positionally and the selector by keyword only; counting its positionals
#: reported ``*widgets`` as an unresolvable address. The `AT-B83-08` invariant caught
#: that the moment ``mount`` entered the set: **the census was reading arguments where
#: it should read parameters.**
FIRST_POSITIONAL_SELECTOR: frozenset[str] = frozenset({
    'action_add_class', 'action_focus', 'action_remove_class', 'action_toggle_class',
    'add_pane', 'add_tab', 'click', 'disable', 'disable_tab', 'double_click', 'enable',
    'enable_tab', 'exclude', 'filter', 'focus_next', 'focus_previous', 'get_child_by_id',
    'get_content_tab', 'get_tab', 'get_widget_by_id', 'hide', 'hide_tab', 'hover',
    'mouse_down', 'mouse_up', 'query', 'query_ancestor', 'query_children',
    'query_exactly_one', 'query_one', 'query_one_optional', 'remove_children',
    'remove_pane', 'remove_tab', 'show', 'show_tab', 'triple_click',
})

#: Every call name that resolves a string to a widget.
ADDRESS_APIS: frozenset[str] = frozenset(ADDRESS_PARAMS)

#: A parameter annotation qualifies as a selector when it admits ``str`` in UNION with a
#: ``type[...]`` or ``Widget`` form. Bare ``str`` does not qualify — that is what
#: :data:`DECLARED_ADDRESS_APIS` is for, and why the two halves are separate.
_ANN_QUERY_RE: re.Pattern[str] = re.compile(r"\bstr\b.*\btype\[|\btype\[.*\bstr\b")
_ANN_PILOT_RE: re.Pattern[str] = re.compile(r"\bWidget\b.*\bstr\b|\bstr\b.*\bWidget\b")

#: A selector's leading ``#``/``.`` must be followed immediately by an identifier
#: character or an interpolation. See the module docstring, definition 1.
SELECTOR_RE: re.Pattern[str] = re.compile(r"^\s*[#.](?:[A-Za-z_]|\{\})")

#: A bare name that is class-like by convention — PascalCase, no leading underscore.
_CLASS_LIKE_RE: re.Pattern[str] = re.compile(r"[A-Z][A-Za-z0-9]*\Z")

#: Textual's reactive hooks. ``watch_x`` / ``validate_x`` / ``compute_x`` are called BY
#: the framework when a reactive attribute changes; a consumer never invokes them to
#: address a widget. Excluding them is a rule about a **documented framework
#: convention**, not a list of inconvenient names — which is the distinction that keeps
#: this derivation honest. Measured: removes 3, none of them called anywhere in s19_app.
_REACTIVE_HOOK_RE: re.Pattern[str] = re.compile(r"(watch|validate|compute)_")

#: Selector-shaped strings longer than this are prose that happens to open with a
#: ``#`` — assertion messages naming an id are the common case.
MAX_SELECTOR_LEN: int = 80

SCANNED_DIRS: tuple[str, ...] = ("s19_app", "tests")


@dataclass
class AddressSite:
    """One call-site argument that addresses a widget.

    Attributes:
        file: Repo-relative path, forward slashes.
        line: 1-indexed line of the argument expression.
        api: The address API called (``query_one``, ``click``, ...).
        form: How the argument is written — ``literal``, ``type``, ``fstring``,
            ``name``, or the AST node type for anything else.
        shape: For f-strings, the literal text with each interpolation as ``{}``.
        interp: For f-strings, the AST node type inside each pair of braces.
        note: A classification the reader may disagree with, never a reason the
            row was hidden. Currently only ``'hex colour'``.
    """

    file: str
    line: int
    api: str
    form: str
    shape: str | None = None
    interp: list[str] = field(default_factory=list)
    note: str = ""


@dataclass
class Census:
    """Everything one run measured.

    Attributes:
        sites: Every argument passed to an address API.
        loose: Selector-shaped f-strings NOT sitting in an address argument.
        files: Count of Python files parsed.
    """

    sites: list[AddressSite] = field(default_factory=list)
    loose: list[AddressSite] = field(default_factory=list)
    indirect: list[AddressSite] = field(default_factory=list)
    files: int = 0


def iter_python_files(root: Path) -> Iterator[Path]:
    """Yield every Python file the census covers.

    Args:
        root: Repository root.

    Returns:
        Iterator over ``.py`` paths under :data:`SCANNED_DIRS`, sorted for
        determinism so two runs on one commit produce byte-identical output.

    Data Flow:
        root -> SCANNED_DIRS -> rglob -> sorted paths -> :func:`census`

    Dependencies:
        Uses: :data:`SCANNED_DIRS`.
        Used by: :func:`census`.
    """
    paths: list[Path] = []
    for name in SCANNED_DIRS:
        paths.extend((root / name).rglob("*.py"))
    return iter(sorted(paths))


def fstring_shape(node: ast.JoinedStr) -> str:
    """Render an f-string as its literal text with interpolations as ``{}``.

    Args:
        node: The f-string node.

    Returns:
        e.g. ``'#log_line_{}'`` for ``f"#log_line_{i}"``.

    Data Flow:
        JoinedStr -> per-value literal or '{}' -> joined shape -> :func:`is_selector`

    Dependencies:
        Used by: :func:`is_selector`, :func:`census`.
    """
    parts: list[str] = []
    for value in node.values:
        if isinstance(value, ast.Constant) and isinstance(value.value, str):
            parts.append(value.value)
        else:
            parts.append("{}")
    return "".join(parts)


def interpolation_kinds(node: ast.JoinedStr) -> list[str]:
    """Report the AST node type inside each interpolation.

    Args:
        node: The f-string node.

    Returns:
        e.g. ``['Name']`` for ``f"#{widget_id}"``, ``['Subscript']`` for
        ``f"#{_WINDOW_BODY[win_id]}"``.

    Data Flow:
        JoinedStr -> FormattedValue.value types -> taxonomy rows in :func:`report`

    Dependencies:
        Used by: :func:`census`.

    Note:
        This distinction is not cosmetic: it is the whole difference between the
        44 sites a naive shape-only grouping calls "strict ``f'#{var}'``" and the
        46 it actually collapses together.
    """
    return [
        type(value.value).__name__
        for value in node.values
        if isinstance(value, ast.FormattedValue)
    ]


def is_selector(shape: str) -> bool:
    """Decide whether an f-string shape is a CSS selector.

    Args:
        shape: Output of :func:`fstring_shape`.

    Returns:
        True when the shape opens with ``#``/``.`` immediately followed by an
        identifier character or interpolation, carries no newline, and is shorter
        than :data:`MAX_SELECTOR_LEN`.

    Data Flow:
        shape -> SELECTOR_RE -> selector-shaped population -> :func:`report`

    Dependencies:
        Uses: :data:`SELECTOR_RE`, :data:`MAX_SELECTOR_LEN`.
        Used by: :func:`census`.

    Example:
        >>> is_selector("#log_line_{}")
        True
        >>> is_selector("## Variant: {}")
        False
        >>> is_selector("... {} more ranges")
        False
    """
    if "\n" in shape or len(shape) > MAX_SELECTOR_LEN:
        return False
    return bool(SELECTOR_RE.match(shape))


def is_hex_colour(node: ast.JoinedStr) -> bool:
    """Decide whether a ``#``-leading f-string is an RGB colour, not a selector.

    Args:
        node: An f-string already known to be selector-shaped.

    Returns:
        True for ``f"#{r:02x}{g:02x}{b:02x}"`` — all interpolations, every one
        carrying a hex format spec.

    Data Flow:
        JoinedStr -> shape is '#' + only interpolations -> specs all hex -> flagged
        in :func:`report` rather than dropped

    Dependencies:
        Uses: :func:`fstring_shape`.
        Used by: :func:`report`.

    Note:
        This classifies rather than excludes, on purpose. Two of these exist in the
        tree and both are genuinely colours — but a census that silently drops rows
        it judged uninteresting is indistinguishable from one with a blind spot.
        The reader sees the row and the label, and can disagree with the label.
    """
    if not re.fullmatch(r"#(\{\})+", fstring_shape(node).strip()):
        return False
    specs = [
        value.format_spec
        for value in node.values
        if isinstance(value, ast.FormattedValue)
    ]
    if not specs or any(spec is None for spec in specs):
        return False
    return all(
        isinstance(spec, ast.JoinedStr) and fstring_shape(spec).lower().endswith("x")
        for spec in specs
    )


def format_spec_nodes(tree: ast.AST) -> set[int]:
    """Collect the ids of every ``JoinedStr`` that is a format spec, not a string.

    Args:
        tree: A parsed module.

    Returns:
        ``id()`` values of the format-spec nodes, for identity exclusion.

    Data Flow:
        module -> FormattedValue.format_spec -> excluded ids -> :func:`census`

    Dependencies:
        Used by: :func:`census`.

    Note:
        ``f"{value:#x}"`` parses its ``:#x`` spec as a nested ``JoinedStr``. Without
        this exclusion the census reports twelve phantom ``#x`` selectors — the
        second-largest source of error found while building this module.
    """
    return {
        id(node.format_spec)
        for node in ast.walk(tree)
        if isinstance(node, ast.FormattedValue) and node.format_spec is not None
    }


def called_name(node: ast.Call) -> str | None:
    """Return the called function's bare name, attribute or plain.

    Args:
        node: A call node.

    Returns:
        ``'query_one'`` for both ``query_one(...)`` and ``app.query_one(...)``;
        None when the callee is an expression rather than a name.

    Data Flow:
        Call.func -> Attribute.attr | Name.id -> ADDRESS_APIS membership

    Dependencies:
        Used by: :func:`census`.
    """
    func = node.func
    if isinstance(func, ast.Attribute):
        return func.attr
    if isinstance(func, ast.Name):
        return func.id
    return None


def _argument_form(arg: ast.expr) -> str:
    """Classify how one address argument is written.

    Args:
        arg: The argument expression.

    Returns:
        ``'literal'``, ``'name'`` (a bare identifier — split into class-like and not
        by :func:`resolves_to_class_like`, because "overwhelmingly a widget class" was
        an adverb standing in for 142-vs-41), ``'fstring'``, or ``'other:<NodeType>'``.

    Dependencies:
        Used by: :func:`census`.
    """
    if isinstance(arg, ast.Constant) and isinstance(arg.value, str):
        return "literal"
    if isinstance(arg, ast.JoinedStr):
        return "fstring"
    if isinstance(arg, ast.Name):
        return "name"
    return "other:" + type(arg).__name__


def resolves_to_class_like(name: str) -> bool:
    """Is this bare name a widget class by convention, or something else?

    Args:
        name: The identifier passed as an address argument.

    Returns:
        True for PascalCase names (``Input``, ``Button``) — type-addressing, resolvable
        by symbol. False for everything else, including ``selector`` and
        ``_B78_RUN_ENTRY``.

    Data Flow:
        ast.Name.id -> _CLASS_LIKE_RE -> the report's name split (:func:`report`)

    Dependencies:
        Uses: :data:`_CLASS_LIKE_RE`.
        Used by: :func:`report`.

    Note:
        A convention, not a resolution — this does not follow imports. It exists because
        "overwhelmingly type-addressing" was an adverb standing in for a number; measured,
        the split is 142 class-like against 41 that are not, and the 41 are where a
        computed selector would hide.

    Example:
        >>> resolves_to_class_like("Input"), resolves_to_class_like("selector")
        (True, False)
    """
    return bool(_CLASS_LIKE_RE.match(name))


def is_candidate_method(name: str) -> bool:
    """Can a method with this name be an address API a consumer calls?

    Args:
        name: The method name.

    Returns:
        False for private methods and for Textual's reactive hooks.

    Data Flow:
        method name -> both derivation passes -> the derived set

    Dependencies:
        Uses: :data:`_REACTIVE_HOOK_RE`.
        Used by: :func:`_textual_methods` and the annotation pass of
            :func:`derive_address_params` — **both**, which is the point.

    Note:
        This exists as ONE function because it was briefly two filters: the collection
        pass excluded privates and hooks while the annotation pass did not, so three
        private methods walked back into the set through the second door. The census
        reported 43 where the rule said 40 and nothing complained. A criterion applied
        in one of two places is not a criterion.

    Example:
        >>> is_candidate_method("query_one"), is_candidate_method("_move_focus")
        (True, False)
        >>> is_candidate_method("watch_active")
        False
    """
    if name.startswith("_"):
        return False
    return not _REACTIVE_HOOK_RE.match(name)


def _textual_methods() -> dict[tuple[str, str], tuple[str, list[str]]]:
    """Every method defined in Textual: ``(class, name) -> (source, param names)``.

    Returns:
        Source text and the ordered parameter names (``self`` dropped) of each method.

    Dependencies:
        Used by: :func:`derive_address_params`.

    Note:
        Methods whose source cannot be retrieved (C extensions, dynamically built) are
        skipped. They define no query API; the skip is silent because the alternative —
        failing on a Textual internal — would make this tool hostage to a dependency.
    """
    import importlib
    import pkgutil
    import textwrap

    import textual

    out: dict[tuple[str, str], tuple[str, list[str]]] = {}
    for mod_info in pkgutil.walk_packages(textual.__path__, "textual."):
        try:
            module = importlib.import_module(mod_info.name)
        except Exception:
            continue
        for _, cls in inspect.getmembers(module, inspect.isclass):
            if not cls.__module__.startswith("textual"):
                continue
            for fname, fn in inspect.getmembers(cls, inspect.isfunction):
                if not is_candidate_method(fname) or (cls.__name__, fname) in out:
                    continue
                try:
                    src = textwrap.dedent(inspect.getsource(fn))
                    sig = inspect.signature(fn)
                except (OSError, TypeError, ValueError):
                    continue
                # R1 — an address is a string, so the parameter must be ANNOTATED as
                # one. An earlier revision also kept unannotated parameters, arguing
                # "absence of a type is not evidence of a non-string". Measured, that
                # admitted exactly one method (`TextualHandler.handle`, whose `record`
                # is a LogRecord) and no true positive. The looser rule bought nothing
                # and cost a name the set could not justify.
                params = [
                    name for name, p in sig.parameters.items()
                    if name != "self" and "str" in str(p.annotation)
                ]
                out[(cls.__name__, fname)] = (src, params)
    return out


def _params_reaching(source: str, sinks: frozenset[str], params: list[str]) -> set[str]:
    """Which of `params` flow into a call to one of `sinks`?

    Args:
        source: The method's source text.
        sinks: Call names that resolve a string to a widget.
        params: The method's parameter names — **already filtered to those that can
            hold a string**; see the note.

    Returns:
        The subset of `params` whose value reaches a sink — directly, inside an
        f-string, or through a local assignment chain (3 rounds).

    Dependencies:
        Uses: :func:`called_name`.
        Used by: :func:`derive_address_params`.

    Note:
        The caller must pre-filter `params` by annotation. Measured without that filter,
        the fixed point promoted 150 methods and 78 distinct parameter names — `console`,
        `crop`, `base_style`, `callback` — because a method that merely *forwards* a value
        into a query becomes a sink and contaminates its own callers transitively. An
        address is a string; a parameter that cannot hold one cannot be an address. The
        filter is derived from annotations, never a list of plausible names.
    """
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return set()
    fn = next((n for n in ast.walk(tree)
               if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))), None)
    if fn is None or not params:
        return set()

    tainted = set(params)
    for _ in range(3):
        grew = False
        for node in ast.walk(fn):
            if isinstance(node, ast.Assign):
                names = {n.id for n in ast.walk(node.value) if isinstance(n, ast.Name)}
                if names & tainted:
                    for tgt in node.targets:
                        if isinstance(tgt, ast.Name) and tgt.id not in tainted:
                            tainted.add(tgt.id)
                            grew = True
        if not grew:
            break

    reaching: set[str] = set()
    for node in ast.walk(fn):
        if not isinstance(node, ast.Call) or called_name(node) not in sinks:
            continue
        for arg in list(node.args) + [k.value for k in node.keywords]:
            for sub in ast.walk(arg):
                if isinstance(sub, ast.Name) and sub.id in tainted and sub.id in params:
                    reaching.add(sub.id)
    return reaching


@functools.lru_cache(maxsize=1)
def derive_address_params() -> tuple[dict[str, set[str]], set[str]]:
    """Derive, from Textual itself, every address API AND which parameter carries it.

    Returns:
        ``(params_by_method, first_positional_methods)`` — the selector parameter names
        of each address method, and the subset whose FIRST parameter is one of them.

    Data Flow:
        annotation pass -> seed methods -> taint fixed point -> params per method
        -> compared against :data:`ADDRESS_PARAMS` by the AT-B83-05 guard

    Dependencies:
        Uses: :func:`_textual_methods`, :func:`_params_reaching`,
            :data:`_ANN_QUERY_RE`, :data:`_ANN_PILOT_RE`.
        Used by: ``tests/test_address_census.py``.

    Note:
        **Two passes, and the second needs the first.** Annotation shape finds the query
        family (`query`, `query_one`, `click`, `mount`, …). Taint then propagates from
        those as sinks and reaches the methods whose parameter is a plain ``str`` —
        `get_widget_by_id`, `action_add_class`, and the per-id families on `Tabs` /
        `TabbedContent` / `ContentSwitcher` that no annotation reveals.

        Seeding taint from `parse_selectors`/`DOMQuery` alone was measured and derives
        **1 of 6**; seeding from the annotation pass derives **6 of 6** plus 23 more.
        That is not circular — the seeds are themselves derived, never written here.

        Costs ~27s. That is the price of retiring a hand-maintained list, and it was an
        explicit operator decision (+1.7% of the suite's wall clock).
    """
    methods = _textual_methods()

    params_by: dict[str, set[str]] = {}
    first_pos: set[str] = set()

    def record(name: str, hits: set[str], params: list[str]) -> None:
        params_by.setdefault(name, set()).update(hits)
        if params and params[0] in hits:
            first_pos.add(name)

    # --- pass 1: annotation shape -------------------------------------------------
    import importlib
    import pkgutil

    import textual

    for mod_info in pkgutil.walk_packages(textual.__path__, "textual."):
        try:
            module = importlib.import_module(mod_info.name)
        except Exception:
            continue
        for _, cls in inspect.getmembers(module, inspect.isclass):
            if not cls.__module__.startswith("textual"):
                continue
            for fname, fn in inspect.getmembers(cls, inspect.isfunction):
                if not is_candidate_method(fname):
                    continue
                try:
                    sig = inspect.signature(fn)
                except (ValueError, TypeError):
                    continue
                names = [p for p in sig.parameters if p != "self"]
                hits = {
                    pname for pname, param in sig.parameters.items()
                    if pname != "self"
                    and (_ANN_QUERY_RE.search(str(param.annotation))
                         or _ANN_PILOT_RE.search(str(param.annotation)))
                }
                if hits:
                    record(fname, hits, names)

    # --- pass 2: taint, seeded by pass 1 ------------------------------------------
    sinks = frozenset(params_by) | frozenset({"parse_selectors", "_get_by_id", "DOMQuery"})
    for _round in range(6):
        added = False
        for (_cls, fname), (src, params) in methods.items():
            if fname in params_by:
                continue
            hits = _params_reaching(src, sinks, params)
            if hits:
                record(fname, hits, params)
                sinks = sinks | {fname}
                added = True
        if not added:
            break

    return {k: v for k, v in params_by.items() if v}, first_pos


def census_source(source: str, filename: str) -> tuple[list[AddressSite], list[AddressSite]]:
    """Census one module's source. The pure core — no filesystem, no globbing.

    Args:
        source: Python source text.
        filename: Label used for the ``file`` field of every row.

    Returns:
        ``(sites, loose)`` — address-API arguments, and selector-shaped f-strings
        that sit outside any address argument.

    Raises:
        SyntaxError: If ``source`` does not parse. Deliberately not caught; see
            :func:`census`.

    Data Flow:
        source -> ast.parse -> address calls -> sites
                            -> leftover selector-shaped f-strings -> loose

    Dependencies:
        Uses: :func:`format_spec_nodes`, :func:`called_name`, :func:`fstring_shape`,
            :func:`interpolation_kinds`, :func:`is_selector`, :func:`is_hex_colour`.
        Used by: :func:`census`, and every synthetic-fixture test — which is why it
            exists as a separate function at all.

    Example:
        >>> sites, loose = census_source('app.query_one(f"#{x}")', "t.py")
        >>> sites[0].form, sites[0].shape
        ('fstring', '#{}')
    """
    tree = ast.parse(source, filename=filename)
    specs = format_spec_nodes(tree)
    sites: list[AddressSite] = []
    loose: list[AddressSite] = []
    addressed: set[int] = set()

    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        api = called_name(node)
        if api not in ADDRESS_APIS:
            continue
        # Parameters, not arguments. Only the FIRST positional of an API that takes
        # its selector positionally, plus keywords whose name carries a selector.
        # Scanning args alone leaves `query_one(selector=f"#{x}")` invisible; scanning
        # every arg reports `mount(*widgets)` as an address. Both are wrong.
        arguments: list[ast.expr] = []
        if node.args and api in FIRST_POSITIONAL_SELECTOR:
            arguments.append(node.args[0])
        selector_params = ADDRESS_PARAMS[api]
        arguments.extend(
            kw.value for kw in node.keywords if kw.arg in selector_params
        )
        for arg in arguments:
            site = AddressSite(filename, arg.lineno, api, _argument_form(arg))
            if isinstance(arg, ast.JoinedStr):
                site.shape = fstring_shape(arg)
                site.interp = interpolation_kinds(arg)
                addressed.add(id(arg))
            elif isinstance(arg, ast.Name):
                # The identifier IS the shape of a bare-name argument, and the report's
                # class-like split needs it. Without this the split silently reads zero.
                site.shape = arg.id
            sites.append(site)

    for node in ast.walk(tree):
        if not isinstance(node, ast.JoinedStr):
            continue
        if id(node) in specs or id(node) in addressed:
            continue
        shape = fstring_shape(node)
        if is_selector(shape):
            loose.append(
                AddressSite(filename, node.lineno, api="-", form="loose",
                            shape=shape, interp=interpolation_kinds(node),
                            note="hex colour" if is_hex_colour(node) else "")
            )
    return sites, loose


def find_indirect_addresses(source: str, filename: str) -> list[AddressSite]:
    """Selector-shaped f-strings that reach an address API through a local variable.

    Args:
        source: Python source text.
        filename: Label for the ``file`` field.

    Returns:
        One row per site where ``sel = f"#{x}"`` is later passed to an address API in
        the same function — the pattern the census otherwise reports split in two.

    Raises:
        SyntaxError: If ``source`` does not parse.

    Data Flow:
        source -> assignments of selector-shaped f-strings -> names used in an address
        argument within the same function -> rows

    Dependencies:
        Uses: :func:`fstring_shape`, :func:`is_selector`, :func:`called_name`,
            :data:`ADDRESS_PARAMS`, :data:`FIRST_POSITIONAL_SELECTOR`.
        Used by: :func:`report`, and the `AT-B83-10` guard.

    Note:
        **This is a detector, not flow tracking.** It recognises ONE shape — assign then
        use, inside one function — and claims nothing about longer chains. The census
        proper follows zero hops by design; without this, `sel = f"#{x}"` followed by
        `query_one(sel)` reports as an unrelated loose f-string plus a bare name, and
        neither row says "computed address". Measured on the tree today: **0 sites**.
        The value is that the day one appears it is visible, rather than absent from a
        report that looks complete.

    Example:
        >>> rows = find_indirect_addresses(
        ...     'def f(app, x):\\n sel = f"#{x}"\\n app.query_one(sel)\\n', "t.py")
        >>> rows[0].form, rows[0].shape
        ('fstring-via-name', '#{}')
    """
    tree = ast.parse(source, filename=filename)
    out: list[AddressSite] = []
    # `ast.walk` from Module re-enters every FunctionDef, so a site inside a function is
    # visited under both scopes. Dedupe by call site, not by scope.
    seen: set[tuple[int, str]] = set()

    for scope in ast.walk(tree):
        if not isinstance(scope, (ast.FunctionDef, ast.AsyncFunctionDef, ast.Module)):
            continue
        # name -> the selector-shaped f-string assigned to it, in this scope
        assigned: dict[str, ast.JoinedStr] = {}
        for node in ast.walk(scope):
            if not isinstance(node, ast.Assign) or not isinstance(node.value, ast.JoinedStr):
                continue
            if not is_selector(fstring_shape(node.value)):
                continue
            for target in node.targets:
                if isinstance(target, ast.Name):
                    assigned[target.id] = node.value
        if not assigned:
            continue

        for node in ast.walk(scope):
            if not isinstance(node, ast.Call):
                continue
            api = called_name(node)
            if api not in ADDRESS_APIS:
                continue
            candidates: list[ast.expr] = []
            if node.args and api in FIRST_POSITIONAL_SELECTOR:
                candidates.append(node.args[0])
            candidates.extend(
                kw.value for kw in node.keywords if kw.arg in ADDRESS_PARAMS[api]
            )
            for arg in candidates:
                if isinstance(arg, ast.Name) and arg.id in assigned:
                    key = (node.lineno, arg.id)
                    if key in seen:
                        continue
                    seen.add(key)
                    fstr = assigned[arg.id]
                    out.append(AddressSite(
                        filename, node.lineno, api, "fstring-via-name",
                        shape=fstring_shape(fstr),
                        interp=interpolation_kinds(fstr),
                        note=f"assigned to {arg.id!r} at line {fstr.lineno}",
                    ))
    return out


def census(root: Path) -> Census:
    """Measure every address site and every loose selector-shaped f-string.

    Args:
        root: Repository root.

    Returns:
        A :class:`Census`.

    Raises:
        SyntaxError: If a scanned file does not parse. Deliberately not caught —
            a census that silently skips a file it could not read is the vacuous
            shape this module exists to avoid.

    Data Flow:
        files -> ast.parse -> address-API calls -> AddressSite rows
                           -> selector-shaped f-strings outside them -> loose rows

    Dependencies:
        Uses: :func:`iter_python_files`, :func:`format_spec_nodes`,
            :func:`called_name`, :func:`fstring_shape`, :func:`is_selector`.
        Used by: :func:`report`, :func:`main`.
    """
    out = Census()
    for path in iter_python_files(root):
        rel = path.relative_to(root).as_posix()
        text = path.read_text(encoding="utf-8")
        sites, loose = census_source(text, rel)
        out.files += 1
        out.sites.extend(sites)
        out.loose.extend(loose)
        out.indirect.extend(find_indirect_addresses(text, rel))
    return out


def report(data: Census) -> None:
    """Print the census as the human-readable table.

    Args:
        data: Output of :func:`census`.

    Returns:
        None. Writes to stdout, ASCII only — this repo is developed on a cp1252
        console and a UnicodeEncodeError in a measurement tool is a measurement
        that did not happen.

    Data Flow:
        Census -> Counter aggregates -> stdout

    Dependencies:
        Used by: :func:`main`.
    """
    forms = Counter(s.form for s in data.sites)
    fstrings = [s for s in data.sites if s.form == "fstring"]
    strict = [s for s in fstrings if s.shape == "#{}" and s.interp == ["Name"]]
    subscript = [s for s in fstrings if s.shape == "#{}" and s.interp != ["Name"]]
    extra = [s for s in fstrings if s.shape != "#{}"]
    other_door = [s for s in fstrings if s.api not in QUERY_APIS]

    print("=" * 74)
    print("ADDRESS CENSUS -- %d files" % data.files)
    print("=" * 74)
    print("argument forms passed to an address API:")
    for form, count in forms.most_common():
        print("  %-24s %5d" % (form, count))
    print("  %-24s %5d" % ("TOTAL", sum(forms.values())))
    print()
    print("computed addresses (f-string arguments): %d" % len(fstrings))
    print("  strict f\"#{name}\"                    : %d" % len(strict))
    print("  f\"#{...}\" with a non-Name expression : %d" % len(subscript))
    for site in subscript:
        print("      %-22s %-12s %s:%d"
              % (site.shape, ",".join(site.interp), site.file, site.line))
    print("  extra literal inside the selector    : %d" % len(extra))
    for site in extra:
        print("      %-24s %s:%d" % (site.shape, site.file, site.line))
    print()
    print("  reached through a door that is NOT query_one/query: %d" % len(other_door))
    for site in other_door:
        print("      %-10s %-14s %s:%d"
              % (site.shape, site.api, site.file, site.line))
    print("  (a detector watching only the query pair does not see these)")
    print()
    classified = [s for s in data.loose if s.note]
    print("selector-shaped f-strings NOT in an address argument: %d"
          % len(data.loose))
    print("  of those, classified as not-a-selector: %d  (shown, never dropped)"
          % len(classified))
    for site in data.loose:
        print("      %-46s %-12s %s:%d"
              % (repr(site.shape)[:46], site.note, site.file, site.line))
    print()
    class_like = [s for s in data.sites
                  if s.form == "name" and resolves_to_class_like(s.shape or "")]
    print("NOTE on 'name': %d of %d resolve to a class-like symbol (type-addressing);"
          % (len(class_like), forms.get("name", 0)))
    print("      the rest are variables, and a variable is where a computed selector")
    print("      hides one assignment away. Measured, not asserted.")
    print()
    print("indirect addresses (f-string -> variable -> address API): %d"
          % len(data.indirect))
    for site in data.indirect:
        print("      %-14s %-22s %s:%d"
              % (site.shape, site.note, site.file, site.line))
    if not data.indirect:
        print("      none -- the census follows zero hops, and this is what makes")
        print("      that premise checkable rather than merely declared")
    print()
    print("The 'computed addresses' section IS the set of sites whose address cannot be")
    print("resolved by reading the call. A validator can recognise the SITE; it cannot")
    print("resolve the VALUE. These are where human judgement is obligatory -- which is")
    print("the whole claim, and it is about this code, not about any rule that reads it.")


def main(argv: list[str] | None = None) -> int:
    """Entry point.

    Args:
        argv: Command-line arguments; defaults to ``sys.argv[1:]``.

    Returns:
        Process exit code; 0 always — this is a measurement, not a gate. A guard
        built on it should import :func:`census` and assert on the numbers itself.

    Data Flow:
        argv -> census(root) -> report | json -> stdout

    Dependencies:
        Uses: :func:`census`, :func:`report`.

    Example::

        python tools/address_census.py --json | jq '.sites | length'
    """
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parent.parent,
                        help="repository root (default: the repo this file lives in)")
    parser.add_argument("--json", action="store_true", help="machine-readable output")
    args = parser.parse_args(argv)

    data = census(args.root)
    if args.json:
        json.dump(
            {"files": data.files,
             "sites": [vars(s) for s in data.sites],
             "loose": [vars(s) for s in data.loose],
             "indirect": [vars(s) for s in data.indirect]},
            sys.stdout, indent=1,
        )
        print()
    else:
        report(data)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
